//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("idiomas.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo en ({0}:{1})
        ///Error Obteniendo Info.
        /// </summary>
        public static string CLUSTER_ERROR_01 {
            get {
                return ResourceManager.GetString("CLUSTER_ERROR_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo en ({0}:{1})
        ///No Responde.
        /// </summary>
        public static string CLUSTER_ERROR_02 {
            get {
                return ResourceManager.GetString("CLUSTER_ERROR_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo en ({0}:{1})
        ///Error Solicitando Info.
        /// </summary>
        public static string CLUSTER_ERROR_03 {
            get {
                return ResourceManager.GetString("CLUSTER_ERROR_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipos Externos.
        /// </summary>
        public static string EquiposExternos {
            get {
                return ResourceManager.GetString("EquiposExternos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Almacenar Eventos PTT / SQH.
        /// </summary>
        public static string EVENTOSPTT {
            get {
                return ResourceManager.GetString("EVENTOSPTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        public static string GENERAL {
            get {
                return ResourceManager.GetString("GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulo de Configuracion Local.
        /// </summary>
        public static string GW_CFGL_MODULE {
            get {
                return ResourceManager.GetString("GW_CFGL_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasarela.
        /// </summary>
        public static string GW_GLOBAL_MODULE {
            get {
                return ResourceManager.GetString("GW_GLOBAL_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Configuracion.
        /// </summary>
        public static string GW_NEW_CONFIG {
            get {
                return ResourceManager.GetString("GW_NEW_CONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulo SIP.
        /// </summary>
        public static string GW_SIP_MODULE {
            get {
                return ResourceManager.GetString("GW_SIP_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulo SNMP.
        /// </summary>
        public static string GW_SNMP_MODULE {
            get {
                return ResourceManager.GetString("GW_SNMP_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        public static string GWS_Principal {
            get {
                return ResourceManager.GetString("GWS_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reserva.
        /// </summary>
        public static string GWS_Reserva {
            get {
                return ResourceManager.GetString("GWS_Reserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz de Recurso no Disponible.
        /// </summary>
        public static string GWS_ResInterfazNo {
            get {
                return ResourceManager.GetString("GWS_ResInterfazNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz de Recurso si Disponible.
        /// </summary>
        public static string GWS_ResInterfazSi {
            get {
                return ResourceManager.GetString("GWS_ResInterfazSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Obteniendo Version.
        /// </summary>
        public static string GWS_VersionError {
            get {
                return ResourceManager.GetString("GWS_VersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historicos.
        /// </summary>
        public static string HISTORICO {
            get {
                return ResourceManager.GetString("HISTORICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunidad para Lectura.
        /// </summary>
        public static string IDGETCOMM {
            get {
                return ResourceManager.GetString("IDGETCOMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunidad para Escritura.
        /// </summary>
        public static string IDSETCOMM {
            get {
                return ResourceManager.GetString("IDSETCOMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NBX Activado en.
        /// </summary>
        public static string NBX_Activo {
            get {
                return ResourceManager.GetString("NBX_Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NBX Caido en.
        /// </summary>
        public static string NBX_Caido {
            get {
                return ResourceManager.GetString("NBX_Caido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Hay Servicio NBX MASTER en el Sistema.
        /// </summary>
        public static string NBX_NoService {
            get {
                return ResourceManager.GetString("NBX_NoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Sincronizado.
        /// </summary>
        public static string NoSincronizado {
            get {
                return ResourceManager.GetString("NoSincronizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Hay Servidor NTP en el Sistema.
        /// </summary>
        public static string NTP_NoServer {
            get {
                return ResourceManager.GetString("NTP_NoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor NTP Conectado.
        /// </summary>
        public static string NTP_ServerConnected {
            get {
                return ResourceManager.GetString("NTP_ServerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PBX Conectada.
        /// </summary>
        public static string PBX_Conectada {
            get {
                return ResourceManager.GetString("PBX_Conectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PBX Desconectada.
        /// </summary>
        public static string PBX_Desconectada {
            get {
                return ResourceManager.GetString("PBX_Desconectada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        public static string PBX_Desconocida {
            get {
                return ResourceManager.GetString("PBX_Desconocida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sacta.
        /// </summary>
        public static string SACTA {
            get {
                return ResourceManager.GetString("SACTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red SACTA1 Desconectada.
        /// </summary>
        public static string SACTA_LAN1_OFF {
            get {
                return ResourceManager.GetString("SACTA_LAN1_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red SACTA1 Conectada.
        /// </summary>
        public static string SACTA_LAN1_ON {
            get {
                return ResourceManager.GetString("SACTA_LAN1_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red SACTA2 Desconectada.
        /// </summary>
        public static string SACTA_LAN2_OFF {
            get {
                return ResourceManager.GetString("SACTA_LAN2_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red SACTA2 Conectada.
        /// </summary>
        public static string SACTA_LAN2_ON {
            get {
                return ResourceManager.GetString("SACTA_LAN2_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor Dual.
        /// </summary>
        public static string ServidorDual {
            get {
                return ResourceManager.GetString("ServidorDual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronizado.
        /// </summary>
        public static string Sincronizado {
            get {
                return ResourceManager.GetString("Sincronizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Snmp.
        /// </summary>
        public static string SNMP {
            get {
                return ResourceManager.GetString("SNMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto SNMP.
        /// </summary>
        public static string SNMPPORT {
            get {
                return ResourceManager.GetString("SNMPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puerto Escucha TRAPS SNMP.
        /// </summary>
        public static string SNMPTRAPPORT {
            get {
                return ResourceManager.GetString("SNMPTRAPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOP No existe.
        /// </summary>
        public static string TOP_NoExiste {
            get {
                return ResourceManager.GetString("TOP_NoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Sincronizado.
        /// </summary>
        public static string TOP_NoSincronizado {
            get {
                return ResourceManager.GetString("TOP_NoSincronizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronizado.
        /// </summary>
        public static string TOP_Sincronizado {
            get {
                return ResourceManager.GetString("TOP_Sincronizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string USERS {
            get {
                return ResourceManager.GetString("USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V2.
        /// </summary>
        public static string V2 {
            get {
                return ResourceManager.GetString("V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a V3.
        /// </summary>
        public static string V3 {
            get {
                return ResourceManager.GetString("V3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string WAP_MSG_001 {
            get {
                return ResourceManager.GetString("WAP_MSG_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a : Metodo No Permitido.
        /// </summary>
        public static string WAP_MSG_002 {
            get {
                return ResourceManager.GetString("WAP_MSG_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puestos de Operador.
        /// </summary>
        public static string WAP_MSG_003 {
            get {
                return ResourceManager.GetString("WAP_MSG_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasarelas.
        /// </summary>
        public static string WAP_MSG_004 {
            get {
                return ResourceManager.GetString("WAP_MSG_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas.
        /// </summary>
        public static string WAP_MSG_005 {
            get {
                return ResourceManager.GetString("WAP_MSG_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patron de Reloj.
        /// </summary>
        public static string WAP_MSG_008 {
            get {
                return ResourceManager.GetString("WAP_MSG_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PABX Interna.
        /// </summary>
        public static string WAP_MSG_009 {
            get {
                return ResourceManager.GetString("WAP_MSG_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonido.
        /// </summary>
        public static string WAP_MSG_010 {
            get {
                return ResourceManager.GetString("WAP_MSG_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Historico.
        /// </summary>
        public static string WAP_MSG_011 {
            get {
                return ResourceManager.GetString("WAP_MSG_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dias en Historico.
        /// </summary>
        public static string WAP_MSG_012 {
            get {
                return ResourceManager.GetString("WAP_MSG_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencias sin Reconocer.
        /// </summary>
        public static string WAP_MSG_013 {
            get {
                return ResourceManager.GetString("WAP_MSG_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos.
        /// </summary>
        public static string WAP_MSG_014 {
            get {
                return ResourceManager.GetString("WAP_MSG_014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HF /Altavoz HF.
        /// </summary>
        public static string WAP_MSG_015 {
            get {
                return ResourceManager.GetString("WAP_MSG_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestion de Pasarelas.
        /// </summary>
        public static string WAP_MSG_016 {
            get {
                return ResourceManager.GetString("WAP_MSG_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Semana.
        /// </summary>
        public static string WAP_OPT_001 {
            get {
                return ResourceManager.GetString("WAP_OPT_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2 Semanas.
        /// </summary>
        public static string WAP_OPT_002 {
            get {
                return ResourceManager.GetString("WAP_OPT_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Mes.
        /// </summary>
        public static string WAP_OPT_003 {
            get {
                return ResourceManager.GetString("WAP_OPT_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 Meses.
        /// </summary>
        public static string WAP_OPT_004 {
            get {
                return ResourceManager.GetString("WAP_OPT_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6 Meses.
        /// </summary>
        public static string WAP_OPT_005 {
            get {
                return ResourceManager.GetString("WAP_OPT_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 Año.
        /// </summary>
        public static string WAP_OPT_006 {
            get {
                return ResourceManager.GetString("WAP_OPT_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal.
        /// </summary>
        public static string WAP_OPT_007 {
            get {
                return ResourceManager.GetString("WAP_OPT_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unificadas.
        /// </summary>
        public static string WAP_OPT_008 {
            get {
                return ResourceManager.GetString("WAP_OPT_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio sin conexion a la base de Datos.
        /// </summary>
        public static string WEB_DIS_CAUSE_01 {
            get {
                return ResourceManager.GetString("WEB_DIS_CAUSE_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio en Modo Slave....
        /// </summary>
        public static string WEB_DIS_CUASE_02 {
            get {
                return ResourceManager.GetString("WEB_DIS_CUASE_02", resourceCulture);
            }
        }
    }
}
