//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RcsHfSimulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>TXHF01,.1.3.6.1.4.1.7916.8.100.1.1</string>
  <string>TXHF02,.1.3.6.1.4.1.7916.8.100.1.2</string>
  <string>TXHF03,.1.3.6.1.4.1.7916.8.100.1.3</string>
  <string>TXHF04,.1.3.6.1.4.1.7916.8.100.1.4</string>
  <string>TXHF05,.1.3.6.1.4.1.7916.8.100.1.5</string>
  <string>TXHF06,.1.3.6.1.4.1.7916.8.100.1.6</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Transmisores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Transmisores"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.129")]
        public string IpPropia {
            get {
                return ((string)(this["IpPropia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("161")]
        public int PortSnmp {
            get {
                return ((int)(this["PortSnmp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsingStandarOids {
            get {
                return ((bool)(this["UsingStandarOids"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection lastStatus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["lastStatus"]));
            }
            set {
                this["lastStatus"] = value;
            }
        }
    }
}
