//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RcsHfSimulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>TX_VHF_M1;Transmisor;VHF;Main;119000;0;0;0;1</string>
  <string>TX_VHF_M2;Transmisor;VHF;Main;120300;0;0;0;0</string>
  <string>TX_VHF_M3;Transmisor;VHF;Main;121500;0;0;0;0</string>
  <string>TX_VHF_M4;Transmisor;VHF;Main;121750;0;0;0;0</string>
  <string>TX_VHF_M5;Transmisor;VHF;Main;121900;0;0;0;0</string>
  <string>TX_UHF_M1;Transmisor;UHF;Main;243000;0;0;0;0</string>
  <string>TX_UHF_M2;Transmisor;UHF;Main;257800;0;0;0;0</string>
  <string>TX_VHF_N1;Transmisor;VHF;Rsva;;0;0;0;0</string>
  <string>TX_VHF_N2;Transmisor;VHF;Rsva;;0;0;0;0</string>
  <string>TX_UHF_N1;Transmisor;UHF;Rsva;;0;0;0;0</string>
  <string>RX_VHF_M1;Receptor;VHF;Main;119000;0;0;0;0</string>
  <string>RX_VHF_M2;Receptor;VHF;Main;120300;0;0;0;0</string>
  <string>RX_VHF_M3;Receptor;VHF;Main;121500;0;0;0;0</string>
  <string>RX_VHF_M4;Receptor;VHF;Main;121750;0;0;0;0</string>
  <string>RX_VHF_M5;Receptor;VHF;Main;121900;0;0;0;0</string>
  <string>RX_UHF_M1;Receptor;UHF;Main;243000;0;0;0;0</string>
  <string>RX_UHF_M2;Receptor;UHF;Main;257800;0;0;0;0</string>
  <string>RX_VHF_N1;Receptor;VHF;Rsva;;0;0;0;0</string>
  <string>RX_VHF_N2;Receptor;VHF;Rsva;;0;0;0;0</string>
  <string>RX_UHF_N1;Receptor;UHF;Rsva;;0;0;0;0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GearList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GearList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".1.3.6.1.4.1.7916.8.4.1.3.1")]
        public string OidBase {
            get {
                return ((string)(this["OidBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.71")]
        public string IpPropia {
            get {
                return ((string)(this["IpPropia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("161")]
        public int PortSnmp {
            get {
                return ((int)(this["PortSnmp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".1.3.6.1.4.1.7916.8.4.1.1.0")]
        public string OidPregunta {
            get {
                return ((string)(this["OidPregunta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".1.3.6.1.4.1.7916.8.4.1.2.0")]
        public string OidRespuesta {
            get {
                return ((string)(this["OidRespuesta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public uint SipLogLevel {
            get {
                return ((uint)(this["SipLogLevel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PCMA")]
        public string DefaultCodec {
            get {
                return ((string)(this["DefaultCodec"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public uint DefaultDelayBufPframes {
            get {
                return ((uint)(this["DefaultDelayBufPframes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public uint DefaultJBufPframes {
            get {
                return ((uint)(this["DefaultJBufPframes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public uint SndSamplingRate {
            get {
                return ((uint)(this["SndSamplingRate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float RxLevel {
            get {
                return ((float)(this["RxLevel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float TxLevel {
            get {
                return ((float)(this["TxLevel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public uint TsxTout {
            get {
                return ((uint)(this["TsxTout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint InvProceedingIaTout {
            get {
                return ((uint)(this["InvProceedingIaTout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public uint InvProceedingMonitoringTout {
            get {
                return ((uint)(this["InvProceedingMonitoringTout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public uint InvProceedingDiaTout {
            get {
                return ((uint)(this["InvProceedingDiaTout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint InvProceedingRdTout {
            get {
                return ((uint)(this["InvProceedingRdTout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public uint EchoTail {
            get {
                return ((uint)(this["EchoTail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint EchoLatency {
            get {
                return ((uint)(this["EchoLatency"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint RecordingEd137 {
            get {
                return ((uint)(this["RecordingEd137"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public uint KAPeriod {
            get {
                return ((uint)(this["KAPeriod"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint KAMultiplier {
            get {
                return ((uint)(this["KAMultiplier"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection LastStatus {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LastStatus"]));
            }
            set {
                this["LastStatus"] = value;
            }
        }
    }
}
