//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServicioInterfazSactaSoap", Namespace="http://CD40.es/")]
public partial class ServicioInterfazSacta : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetEstadoSactaOperationCompleted;
    
    private System.Threading.SendOrPostCallback StartSactaOperationCompleted;
    
    private System.Threading.SendOrPostCallback EndSactaOperationCompleted;
    
    /// <remarks/>
    public ServicioInterfazSacta() {
        // this.Url = U5kManServer.Properties.u5kManServer.Default.SactaService;   // "http://localhost:51277/InterfazSacta/ServicioInterfazSacta.asmx";
        // this.Url = String.Format("http://192.168.0.211:51277/InterfazSacta/ServicioInterfazSacta.asmx", U5kManServer.Properties.u5kManServer.Default.MySqlServer);
        this.Url = String.Format("http://{0}/nucleodf/u5kcfg/InterfazSacta/ServicioInterfazSacta.asmx", U5kManServer.Properties.u5kManServer.Default.MySqlServer);
    }
    
    /// <remarks/>
    public event GetEstadoSactaCompletedEventHandler GetEstadoSactaCompleted;
    
    /// <remarks/>
    public event StartSactaCompletedEventHandler StartSactaCompleted;
    
    /// <remarks/>
    public event EndSactaCompletedEventHandler EndSactaCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CD40.es/GetEstadoSacta", RequestNamespace="http://CD40.es/", ResponseNamespace="http://CD40.es/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public byte GetEstadoSacta() {
        object[] results = this.Invoke("GetEstadoSacta", new object[0]);
        return ((byte)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetEstadoSacta(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetEstadoSacta", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public byte EndGetEstadoSacta(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte)(results[0]));
    }
    
    /// <remarks/>
    public void GetEstadoSactaAsync() {
        this.GetEstadoSactaAsync(null);
    }
    
    /// <remarks/>
    public void GetEstadoSactaAsync(object userState) {
        if ((this.GetEstadoSactaOperationCompleted == null)) {
            this.GetEstadoSactaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEstadoSactaOperationCompleted);
        }
        this.InvokeAsync("GetEstadoSacta", new object[0], this.GetEstadoSactaOperationCompleted, userState);
    }
    
    private void OnGetEstadoSactaOperationCompleted(object arg) {
        if ((this.GetEstadoSactaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetEstadoSactaCompleted(this, new GetEstadoSactaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CD40.es/StartSacta", RequestNamespace="http://CD40.es/", ResponseNamespace="http://CD40.es/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void StartSacta() {
        this.Invoke("StartSacta", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginStartSacta(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("StartSacta", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndStartSacta(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void StartSactaAsync() {
        this.StartSactaAsync(null);
    }
    
    /// <remarks/>
    public void StartSactaAsync(object userState) {
        if ((this.StartSactaOperationCompleted == null)) {
            this.StartSactaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartSactaOperationCompleted);
        }
        this.InvokeAsync("StartSacta", new object[0], this.StartSactaOperationCompleted, userState);
    }
    
    private void OnStartSactaOperationCompleted(object arg) {
        if ((this.StartSactaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.StartSactaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://CD40.es/EndSacta", RequestNamespace="http://CD40.es/", ResponseNamespace="http://CD40.es/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void EndSacta() {
        this.Invoke("EndSacta", new object[0]);
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEndSacta(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EndSacta", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public void EndEndSacta(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void EndSactaAsync() {
        this.EndSactaAsync(null);
    }
    
    /// <remarks/>
    public void EndSactaAsync(object userState) {
        if ((this.EndSactaOperationCompleted == null)) {
            this.EndSactaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndSactaOperationCompleted);
        }
        this.InvokeAsync("EndSacta", new object[0], this.EndSactaOperationCompleted, userState);
    }
    
    private void OnEndSactaOperationCompleted(object arg) {
        if ((this.EndSactaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EndSactaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void GetEstadoSactaCompletedEventHandler(object sender, GetEstadoSactaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetEstadoSactaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetEstadoSactaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void StartSactaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void EndSactaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
