//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uv5kiTaHfManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uv5kiTaHfManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo no activo....
        /// </summary>
        public static string Equipo_no_activo {
            get {
                return ResourceManager.GetString("Equipo_no_activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a . Equipo Sintonizado....
        /// </summary>
        public static string Equipo_Sintonizado {
            get {
                return ResourceManager.GetString("Equipo_Sintonizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipos.
        /// </summary>
        public static string Equipos {
            get {
                return ResourceManager.GetString("Equipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al Sintonizar.
        /// </summary>
        public static string Error_al_Sintonizar {
            get {
                return ResourceManager.GetString("Error_al_Sintonizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencias (MHz).
        /// </summary>
        public static string Frecuencias {
            get {
                return ResourceManager.GetString("Frecuencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nada que sintonizar.
        /// </summary>
        public static string Nada_que_sintonizar {
            get {
                return ResourceManager.GetString("Nada_que_sintonizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay equipos o frecuencias a sintonizar.
        /// </summary>
        public static string No_hay_equipos_o_frecuencias_a_sintonizar {
            get {
                return ResourceManager.GetString("No_hay_equipos_o_frecuencias_a_sintonizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operacion en Curso. Espere finalizacion.
        /// </summary>
        public static string Operacion_en_Curso {
            get {
                return ResourceManager.GetString("Operacion_en_Curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prox.
        /// </summary>
        public static string Proximo {
            get {
                return ResourceManager.GetString("Proximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sintonizar.
        /// </summary>
        public static string Sintonizar {
            get {
                return ResourceManager.GetString("Sintonizar", resourceCulture);
            }
        }
    }
}
